### ISSUE TITLE
Contributing.md file contains URL broken

### ISSUE THREAD

**Issue by blackc0mb** [chryz-hub/chryz-hub.github.io#102]
**Description**
The contributing.md file contains the broken link to [Code of Conduct](https://github.com/chryz-hub/chryz-hub.github.io/blob/master/CODE_OF_CONDUCT.md) **404 error**

**Stack**

Project stack or language (eg. Frontend):

**Working Environment**

Operating System (eg Linux):

Browser (eg. Chrome):

Device (eg. Laptop or Phone):

**Screenshots**

Please add a screenshot if applicable
![image](https://user-images.githubusercontent.com/76012794/111883002-49161280-897e-11eb-9da4-c2072da62e77.png)

[Optional] **Additional Context**

**Comment by chryzcodez** [comment]
I already did it now, Thanks!

**Comment by chryzcodez** [comment]
I already did it now, Thanks!
