### ISSUE TITLE
Image "our vision" is not shown

### ISSUE THREAD

**Issue by blackc0mb** [chryz-hub/chryz-hub.github.io#104]
**Description**

When you open [chryz-hub.github.io/](chryz-hub.github.io) URL (the content of **Readme.md** file), the image of “our vision” is showed as a HTML code something like this:

`<img width=20% src=”https://thumbs.dreamstime.com/b/basic-rgb-148951998.jpg”>`

I did some test in a local file and with the same TAG it’s shows without any problem, but in the Readme.md file published in [chryz-hub.github.io/](chryz-hub.github.io) the behavior is the described above.

**Stack**

Project stack or language (eg. Frontend):

**Working Environment**

Operating System (eg Linux):

Browser (eg. Chrome):

Device (eg. Laptop or Phone):

**Screenshots**

Please add a screenshot if applicable
![image](https://user-images.githubusercontent.com/76012794/111893066-c87b0480-89c5-11eb-8927-51c2ee0fd482.png)

[Optional] **Additional Context**

**Comment by AmjadNoor** [comment]
I think it is no more after a few week or month because we landing our organisation web page. Instead of docs we landing /root in github page.
