### ISSUE TITLE
Add CSS File

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#107]
https://github.com/chryz-hub/chryz-hub.github.io/tree/master/src

**Comment by namangupta1399** [comment]
@Evavic44 , will start with the work today 👍

**Comment by Evavic44** [comment]
#### Hey @namangupta1399 Can you please wait for @jomefavourite. He'll relate what will be added to the `CSS` file. 
It's just the **_custom styles_** and **_utilities_** we'll be using through out the site that needs to be added. Thanks

**Comment by namangupta1399** [comment]
Yes, will start only after the discussion.

**Comment by jomefavourite** [comment]
Okay, I'll add the css file

**Comment by chryzcodez** [comment]
I've merged it already!

**Comment by jomefavourite** [comment]
> I've merged it already!

Okay good

**Comment by jomefavourite** [comment]
Notice I created two CSS files, one id the global styles where we added things to be reused, and the styles CSS file for the general styling

**Comment by chryzcodez** [comment]
> Notice I created two CSS files, one id the global styles where we added things to be reused, and the styles CSS file for the general styling

I don't really know much on this but I know we're are ready to go🚀😅

**Comment by Evavic44** [comment]
Nice one @jomefavourite, but I think all CSS files should be in the same folder. For easy organization.

**Comment by chryzcodez** [comment]
Please let's deliberate on this as fast as we can!

**Comment by jomefavourite** [comment]
> Nice one @jomefavourite, but I think all CSS files should be in the same folder. For easy organization.

Okay it's cool. You can fix that please.

**Comment by Evavic44** [comment]
Moved the CSS file. @chryzcodez Please can you review and merge.

**Comment by Evavic44** [comment]
I am closing this issue since the CSS files have been added.

**Comment by jomefavourite** [comment]
> I am closing this issue since the CSS files have been added.

The index.html is link to the old location of the moved global.css file. Please could you change it to the link of the new location.

**Comment by Evavic44** [comment]
Okay. Will do that. Thanks for pointing that out.

**Comment by Evavic44** [comment]
Done. 👍🏾
