### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by PrincewillDev** [chryz-hub/chryz-hub.github.io#119]
Please invite me to the GitHub Community Organisation.

- #### Name:

Elebhose Princewill

- #### Discord Username(if exists):

- #### Additional Context: 

On Twitter

I like it because it's an open source community, and it gives me the ability to learn more

**Comment by chryzcodez** [comment]
Please do well to accept the invitation sent to your mail, without it you can't be recognize as a member.

Thanks
