### ISSUE TITLE
Update favicon image location in Index.html

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#124]
#### The typo **(asserts)** in the favicon **link** location is preventing the icon from showing.
![issue-1](https://user-images.githubusercontent.com/62628408/114340352-48246b00-9b4f-11eb-9043-1362cc643eba.PNG)

Correct it to this 👇🏾   #123 
```html
 <link rel="icon" type="image/ico" href="src/assets/images/favicon.ico" />
```

**Comment by AmjadNoor** [comment]
@Evavic44  Can you run this by correcting the link on your localhost or not? 
Because I correct it and run it on my local host but it won't work. 
## Request from Eke
Please can you send me actual favicon image in discord server.

**Comment by Evavic44** [comment]
Okay, I'll send it to you but I wanted First-timers to have a go at this. I'll be adding more issues to be assigned to moderators very soon. @namangupta1399

**Comment by Evavic44** [comment]
Commits and changes for the website should be done on the website branch. Thanks kindly.
