### ISSUE TITLE
minor issues in index.html

### ISSUE THREAD

**Issue by sifa123** [chryz-hub/chryz-hub.github.io#135]
**Description**

I have found some mistakes on line 53,58,59 where I have attached a photo. On line 53, it should be assets not asserts, and I think on line 58, 59 you can delete these extra back-slashes before src

Project stack or language (eg. Frontend):

**Working Environment**

Operating System: Windows

Browser: Chrome

Device: Laptop

**Screenshot**

![Screenshot (62)](https://user-images.githubusercontent.com/63462931/115449263-6f102a80-a23c-11eb-9d5d-e3ebfff09cd4.png)

**Comment by Evavic44** [comment]
Thanks @sifa123 for pointing that out. The asserts typo was recently raised and fixed, so update your fork repo to get the changes. 
For the second one: I think I should raise an issue for that. If I do, can I assign it to you? not just on line 58 & 59 but on every line, for consistency.

**Comment by chryzcodez** [comment]
Thanks @sifa123!

@Evavic44 would work on that!

**Comment by Evavic44** [comment]
@jomefavourite You can also close this and add a new issue for the forward slash

**Comment by jomefavourite** [comment]
> @jomefavourite You can also close this and add a new issue for the forward slash

I'm sorry what forward slash? should I close it when it's not fixed

**Comment by Evavic44** [comment]
Sifa raised 2 issues but one was already fixed, the other is to remove the extra foward slash ``/`` before the src on the css links. And I want you raise it as a new issue and close this one.

**Comment by jomefavourite** [comment]
> Sifa raised 2 issues but one was already fixed, the other is to remove the extra foward slash `/` before the src on the css links. And I want you raise it as a new issue and close this one.

Okay, understood

**Comment by jomefavourite** [comment]
> Sifa raised 2 issues but one was already fixed, the other is to remove the extra foward slash `/` before the src on the css links. And I want you raise it as a new issue and close this one.

But I feel the forward sign should be there with a dot like this `./src/....` to determine the correct path but if you want me to still raise the issue no problem @Evavic44

**Comment by jomefavourite** [comment]
I opened the issue again because I'm waiting for your reply

**Comment by AmjadNoor** [comment]
> > Sifa raised 2 issues but one was already fixed, the other is to remove the extra foward slash `/` before the src on the css links. And I want you raise it as a new issue and close this one.
> 
> But I feel the forward sign should be there with a dot like this `./src/....` to determine the correct path but if you want me to still raise the issue no problem @Evavic44

@jomefavourite @Evavic44 @sifa123 
I wanna say that `./src/.....` or `src/.....` are the same which means the <kbd>src</kbd> folder is present in the  current or same folder.

**Comment by Evavic44** [comment]
![Annotation 2021-04-22 183729](https://user-images.githubusercontent.com/62628408/115761295-1c4c8500-a39a-11eb-8343-03c84e40c4b5.png)
I know it doesn't really add any strong functional value to the code, but for consistency purposes.

**Comment by jomefavourite** [comment]
> ![Annotation 2021-04-22 183729](https://user-images.githubusercontent.com/62628408/115761295-1c4c8500-a39a-11eb-8343-03c84e40c4b5.png)
> I know it doesn't really add any strong functional value to the code, but for consistency purposes.

Okay then, I'll make it like `./src` for all.
