### ISSUE TITLE
Making path in HTML file indentical

### ISSUE THREAD

**Issue by jomefavourite** [chryz-hub/chryz-hub.github.io#136]
**Description**

Make the path for every occurrence in the HTML file be `./src`

**Screenshots**
![img](https://user-images.githubusercontent.com/62628408/115761295-1c4c8500-a39a-11eb-8343-03c84e40c4b5.png)
Please add a screenshot if applicable

**Comment by tanishghosh** [comment]
Hi @jomefavourite ! I have raised a PR resolving this. Can you look into it? 
https://github.com/chryz-hub/chryz-hub.github.io/pull/137

**Comment by jomefavourite** [comment]
> Hi @jomefavourite ! I have raised a PR resolving this. Can you look into it? 
> https://github.com/chryz-hub/chryz-hub.github.io/pull/137

Okay, I'll go through it now
