### ISSUE TITLE
Change Logo Link

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#138]
Change the h1 logo link from `#hero` to `#home` so when users click the logo, it will take them to the homepage instead of the header
```diff
- <h1 class="logo"><a href="#hero"><img src="src/assets/images/chryz-hub-transparent.png" alt="Logo-image"></a></h1>
+ <h1 class="logo"><a href="#home"><img src="src/assets/images/chryz-hub-transparent.png" alt="Logo-image"></a></h1>
```

**Comment by himanshu007-creator** [comment]
HI, i would like to work on this issue. Please assign me this issue

**Comment by Evavic44** [comment]
> HI, i would like to work on this issue. Please assign me this issue

This issue has been fixed already. Thanks for showing interest in our community. Will be adding more issues soon so feel free to ⭐ this repo to get notified.
