### ISSUE TITLE
Remove Inline Style in h1 tag

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#140]
We need to start progressing on building the website and to do that: Firstly
Remove the styling inside the h1 tag in the `html` file
 
```html
<h1 style="text-align: center">Chryz-Hub Community Website</h1>
```

**Comment by namangupta1399** [comment]
Closing the issue @Evavic44

**Comment by Evavic44** [comment]
Okay, thanks.
