### ISSUE TITLE
Delete quick markup 

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#141]
- [ ] Delete the line-break tags `br` in the `html` file.
- [ ] Delete the comment 
![delete-quick-markup-file](https://user-images.githubusercontent.com/62628408/116348261-aefb8280-a7e5-11eb-89b8-a21cce13e41d.png)

**Comment by namangupta1399** [comment]
Closing the issue
Issue resolved by @edmer664
