### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Shen-Yu** [chryz-hub/chryz-hub.github.io#147]
Please invite me to the GitHub Community Organisation.

- #### Name: Eric Shen

- #### Discord Username(if exists):

- #### Additional Context: 

love to contribute to open source

**Comment by chryzcodez** [comment]
Welcome to ChryzHub, @Shen-Yu. In the message above sent by the bot. It is very advisable to link up with us on our platforms. Especially discord, that's where we discuss, share ideas , get access to issues easily. We give advice and answer questions and many more.

So please do well to connect! Thanks
