### ISSUE TITLE
Add social Icons

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#148]
Add the social icons using the following links below.

- [YouTube Link](https://www.youtube.com/channel/UCxro6LYOp3pmmuWDPMg-p1Q)
- [Twitter Link](https://twitter.com/ChryzHub)
- [Discord Link](https://t.co/CxeDvbUiFB?amp=1)

Replace the `#` with the respective links.
```html
      <div class="social">
         <a href="#"><img src="./src/assets/images/youtube.png" alt="YouTube"></a>
         <a href="#"><img src="./src/assets/images/twitter.png" alt="Twitter"></a>  
         <a href="#"><img src="./src/assets/images/discord.png" alt="Discord"></a>
      </div>
```

Please add only one icon so others can contribute too. 😎

- [x]  Youtube
- [x]  Twitter
- [x]  Discord `Note:` _Discord has been added, just replace the link from `#` to the correct link_

**Comment by AmjadNoor** [comment]
@Evavic44 Can I go for it?

**Comment by Evavic44** [comment]
> @Evavic44 Can I go for it?

Sure. Go ahead.

**Comment by JFernando122** [comment]
Can i do one?

**Comment by Evavic44** [comment]
> Can i do one?

Sure @JFernando122.
