### ISSUE TITLE
Style Hero Section

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#159]
### _Add the Hero section to the community website._
__
- [ ] Align the text and icons in the hero section according to the referenced image

- [ ] Font size (Heading): 20px

- [ ] Font size (Paragraph): 1rem

![Untitled](https://user-images.githubusercontent.com/62628408/116823478-a952c380-ab7c-11eb-8147-93e0391655b3.png)
 image.

**Comment by namangupta1399** [comment]
@Evavic44 , pls give some space b/w text and the social media icons.
Thanks.
