### ISSUE TITLE
wrong link in github action

### ISSUE THREAD

**Issue by schmelto** [chryz-hub/chryz-hub.github.io#167]
**Description**

![image](https://user-images.githubusercontent.com/30869493/116969397-7d3b5d80-acb6-11eb-978a-fe96db97353a.png)

https://github.com/chryz-hub/chryz-hub.github.io/blob/master/CONTRIBUTORS.md -> 404

https://github.com/chryz-hub/chryz-hub.github.io/blob/master/MEMBERS.md

ToDo:

Change line `22` and `23` in https://github.com/chryz-hub/chryz-hub.github.io/blob/master/.github/workflows/community.yml from `<a href="https://github.com/chryz-hub/chryz-hub.github.io/blob/master/CONTRIBUTORS.md">here.</a>` to `<a href="https://github.com/chryz-hub/chryz-hub.github.io/blob/master/MEMBERS.md">here.</a>`

**Comment by schmelto** [comment]
Think this would make a `good-first-issue` 🚀

**Comment by chryzcodez** [comment]
Okay, thanks! @schmelto

**Comment by schmelto** [comment]
maybe unassign yourself from this issue @chryzcodez  so everyone know ist up for grab

**Comment by Evavic44** [comment]
Thanks @schmelto for raising this issue. 👍🏾
