### ISSUE TITLE
Add The Vision Section 

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#170]
Add the vision section to the community website using the Figma template.

**Comment by namangupta1399** [comment]
Hey @Evavic44, can I work on this issue?

**Comment by Evavic44** [comment]
> Hey @Evavic44, can I work on this issue? Or if you are working on it, then no issues

Shoot. 👍🏾

**Comment by Evavic44** [comment]
@namangupta1399 What is the status on this?

**Comment by namangupta1399** [comment]
@Evavic44, I've added the **Vision** section back in the hero div. Please review and tell if any other changes are required.

**Comment by Evavic44** [comment]
> @Evavic44 , I've completed the requested changes. Should I make a new PR ?

Sure go ahead.
