### ISSUE TITLE
Add square buttons

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#178]
Using the `btn` class, add the buttons to the hero section after the vision. 
_P.S:_ Use fontawesome for the PR icon.

![add-buttons](https://user-images.githubusercontent.com/62628408/117557438-c864c000-b06a-11eb-9eda-21c5b2c0c896.png)

**Comment by chryzcodez** [comment]
> I will do this

Common go on with it @Te-Stack 🚀
