### ISSUE TITLE
Add fontawesome link to head tag 

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#183]
Add the fontawesome link to the head tag below the `css links` of the `index.html` file. 

#### `Location:` 
Create a new line below `style.css` and paste in the links

![Annotation 2021-05-09 030707](https://user-images.githubusercontent.com/62628408/117558274-c7845c00-b073-11eb-9088-9ccdf6ded874.png)

#### `Fontawesome link` 👇🏾 
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
```

**Comment by Dripsama** [comment]
I would like to work on this

**Comment by chryzcodez** [comment]
You are free man. Start 🚀
