### ISSUE TITLE
I have an idea to add hamburger  menu for mobile view

### ISSUE THREAD

**Issue by IbrahimOlayinka** [chryz-hub/chryz-hub.github.io#187]
**Description**
Currently the community website is only good looking on desktop view, and it would add to the value of the community if the website can be viewed in all types of screens 
A brief description of the ideas:

**Goal**
Add hamburger menu for mobile view

**Comment by chryzcodez** [comment]
Ok, thanks for that!
@Evavic44  and @jomefavourite. Would give you a reply soon.

Also do well to share this on the ideas channel OP n the community discord server. That's one of the reason of having a sever.

**Comment by IbrahimOlayinka** [comment]
Thank you, i will do so to share this idea on the community server

**Comment by jomefavourite** [comment]
Well, the mobile view has been created but could be changed. Here's the link to view it
https://www.figma.com/file/N8ef18pNNEN6Hkht2r44nZ/Chryz-hub?node-id=126%3A22

**Comment by IbrahimOlayinka** [comment]
![chryz-mobile](https://user-images.githubusercontent.com/66981941/117812884-476c1b00-b25a-11eb-819b-e2d14060ab95.png)
![chryz-mobile-menu](https://user-images.githubusercontent.com/66981941/117812900-4affa200-b25a-11eb-82c4-00fcdfe581fa.png)
![chryz-tablet](https://user-images.githubusercontent.com/66981941/117812903-4b983880-b25a-11eb-888c-ab97948e500c.png)
![chryz-tablet-menu](https://user-images.githubusercontent.com/66981941/117812909-4dfa9280-b25a-11eb-94d4-f08a2ab356ff.png)

Here is the screen of the hambrger menu
