### ISSUE TITLE
Make Read more link open a new tab

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#192]

**Comment by namangupta1399** [comment]
Should we add exact content from [Vision.md](https://github.com/chryz-hub/chryz-hub.github.io/blob/master/vision.md) or we would alter it for the website?

**Comment by Evavic44** [comment]
> Should we add exact content from [Vision.md](https://github.com/chryz-hub/chryz-hub.github.io/blob/master/vision.md) or we would alter it for the website?

I think we need to get the complete vision statement from @chryzcodez

**Comment by chryzcodez** [comment]
Okay, I would get this across to the community. Latest tomorrow morning
