### ISSUE TITLE
Pending changes in the readme file

### ISSUE THREAD

**Issue by namangupta1399** [chryz-hub/chryz-hub.github.io#193]
**Description**
Some changes discussed earlier to be made in the [README.md ](https://github.com/chryz-hub/chryz-hub.github.io/blob/master/README.md) file.

Please follow the conversation in #156 for changes.

**Comment by namangupta1399** [comment]
Reviews according to conversation in this [PR](https://github.com/chryz-hub/chryz-hub.github.io/pull/156)
From @Evavic44 
> 1. I feel The Community website README should elaborate more on the community website since this is the repo it lives in with information like: The vision statement, What the community is all about, How to join the community Relevant links of the community, and not really elaborate on how to make a PR since we already have a [How to contribute](https://github.com/chryz-hub/opensource-4-everyone#simple-guide-to-making-a-pull-request-or-contribution) markdown file. 
> 2. Screenshot of our community website.
> 3. If possible a moderators section with images of the moderators of the community.
The texts should be short and simple to read so viewers don't get bored and end up not reading it. 

From @namangupta1399 
> Some fixes to be made in the steps to make a PR
> - In point 7, It should be either git push or git push origin <your branch name>
> - Rewrite point 8

**Comment by jomefavourite** [comment]
I'll be working on this

**Comment by namangupta1399** [comment]
@chryzcodez , are there any other changes required to be made in the README.md ?

**Comment by chryzcodez** [comment]
I don't think so. But if there is, we would do that as we journey along.

**Comment by jomefavourite** [comment]
Okay then
