### ISSUE TITLE
Correct Typo on `Create Pull Requests` and modify the link

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#195]
Correct this typo to:
`Create Pull Request`

New link: https://github.com/chryz-hub/opensource-4-everyone/blob/master/My-PR-Contribution-Practice.md

**Comment by schmelto** [comment]
https://github.com/chryz-hub/chryz-hub.github.io/blob/d77bd6b5f22a1bbc397a96ed4eef03221a7ca8ac/index.html#L86

**Comment by toth2000** [comment]
Thanks, @schmelto.

> https://github.com/chryz-hub/chryz-hub.github.io/blob/d77bd6b5f22a1bbc397a96ed4eef03221a7ca8ac/index.html#L86
