### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Radon333** [chryz-hub/chryz-hub.github.io#198]
Please invite me to the GitHub Community Organisation.

- #### Name: Ranveer Shah

- #### Discord Username(if exists): Billy_Discord#8748

- #### Additional Context: Github

Its fun contributing to open source

**Comment by chryzcodez** [comment]
Hi @Radon333. Please do well to accept the invitation sent to your email address soon. The invitation do expire. Please do that.

And also read the message above to connect with community on discord, Twitter and YouTube. 

Thanks
