### ISSUE TITLE
Improve Community Website: Add "Members" Section

### ISSUE THREAD

**Issue by shubhendumadhukar** [chryz-hub/chryz-hub.github.io#204]
**Description**

As per the community website's mock up, we should have a list of members displayed on the homepage of the website. I have attached a first draft of what the current implementation looks like. Further enhancements could be:
- Pagination, which would be necessary with the growth of community.
- General UI Aesthetics

**Goals**

The aim and objectives of the ideas: Improvement of the current community website.

Attachments:
(Adding links instead of full screenshots)
- [Chryz Hub Mobile UI](https://user-images.githubusercontent.com/10685907/118389385-64805f80-b647-11eb-8fb8-dbd620e78d69.png)
- [Chryz Hub UI](https://user-images.githubusercontent.com/10685907/118389406-76620280-b647-11eb-90ea-e8dc827ebcc4.png)

If the initial implementation looks okay, I can raise a PR for this.

Note that this requires an OAuth token to make api calls.

**Comment by Evavic44** [comment]
> **Description**
> 
> As per the community website's mock up, we should have a list of members displayed on the homepage of the website. I have attached a first draft of what the current implementation looks like. Further enhancements could be:
> 
> * Pagination, which would be necessary with the growth of community.
> * General UI Aesthetics
> 
> **Goals**
> 
> The aim and objectives of the ideas: Improvement of the current community website.
> 
> Attachments:
> (Adding links instead of full screenshots)
> 
> * [Chryz Hub Mobile UI](https://user-images.githubusercontent.com/10685907/118389385-64805f80-b647-11eb-8fb8-dbd620e78d69.png)
> * [Chryz Hub UI](https://user-images.githubusercontent.com/10685907/118389406-76620280-b647-11eb-90ea-e8dc827ebcc4.png)
> 
> If the initial implementation looks okay, I can raise a PR for this.
> 
> Note that this requires an OAuth token to make api calls.

Awesome idea, I agree that we need a members section however there are a few things to consider if this were to be implemented. 
- [ ] The design should match with the template of the community website [here](https://www.figma.com/file/N8ef18pNNEN6Hkht2r44nZ/Chryz-hub?node-id=126%3A22)

**Comment by Evavic44** [comment]
### Suggestions 
- [ ] The design should match with the template of the community website [here](https://www.figma.com/file/N8ef18pNNEN6Hkht2r44nZ/Chryz-hub?node-id=126%3A22)
- [ ] Scrolling through the members section might be a problem as the community grows. Instead we could
- create a dedicated `.html` file for the members and link it to the homepage.
- or create a slider and add members info using the API, like so;
<img src="https://user-images.githubusercontent.com/62628408/118418037-ad1f3380-b6ae-11eb-8e3d-7cc2172b4075.gif" width="500px">
