### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Navachethan-Murugeppa** [chryz-hub/chryz-hub.github.io#227]
Please invite me to the GitHub Community Organisation.

- #### Name: Navachethan Murugeppa

- #### Discord Username(if exists): Navachethan#5533

- #### Additional Context:   I came across this open source organization in github recommended repositories.

  I am a noob in the world of open source so would like to join open source organizations and learn their culture of working together across the globe and more specifically the skills to manage people with different diversities in thought and culture that enhances the quality of open source, and apply the same with my peer organization. I would like to put in my thoughts as well and put effort to work with teams and be a part of open source community soon. Thank you

**Comment by chryzcodez** [comment]
Hi, @Navachethan-Murugeppa 

You are yet to accept the invitation sent to your email address. Please do so now because it expires.
