### ISSUE TITLE
Add project section

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#232]
Using GitHub links and images of our top `3` projects add the project section to the website.

**Comment by namangupta1399** [comment]
Minor fix: 
- [ ] Replace the background with a copyright free image (Unsplash / pexels)

**Comment by Evavic44** [comment]
> Minor fix: 
> - [x] Replace the background of project block with a copyright free image (Unsplash / pexels)

Have the copyright free image been added?

**Comment by namangupta1399** [comment]
> > Minor fix:
> > 
> > * [x]  Replace the background of project block with a copyright free image (Unsplash / pexels)
> 
> Have the copyright free image been added?

Yes
