### ISSUE TITLE
Remove duplicate CSS code 

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#233]
In the `style.css` file, there are multiple code duplicates. 
Merged duplicate.
> Duplicate can be found in line 204 - 298

_verify error and check for more errors_

**Comment by namangupta1399** [comment]
Closing the issue since the PR is merged

**Comment by Evavic44** [comment]
> Closing the issue since the PR is merged

Alright. Thanks.
