### ISSUE TITLE
Use GitHub API to get Project Data

### ISSUE THREAD

**Issue by schmelto** [chryz-hub/chryz-hub.github.io#248]

**Comment by namangupta1399** [comment]
Since we are showing only top 3 project. We should not use GitHub API to fetch all projects. We will be adding a **View More** button. And we can link it to a separate page to show all projects on a separate page. What's your take on this?

**Comment by schmelto** [comment]
> Since we are showing only top 3 project. We should not use GitHub API to fetch all projects. We will be adding a **View More** button. And we can link it to a separate page to show all projects.
> What's your take on this?

I would add a json object in the script that contains all the projects we want to display thus we can use the api to get the description etc.

**Comment by namangupta1399** [comment]
Yeah, this seems better 👍
