### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by JayantGoel001** [chryz-hub/chryz-hub.github.io#250]
Please invite me to the GitHub Community Organisation.

- #### Name:

Jayant Goel
- #### Discord Username(if exists):

- #### Additional Context: 
Github

To become an amazing developer and contribute toward open source

**Comment by chryzcodez** [comment]
You're welcome @JayantGoel001

**Comment by JayantGoel001** [comment]
> You're welcome @JayantGoel001

Thanks @chryzcodez 😁
