### ISSUE TITLE
Why is code in src/assets

### ISSUE THREAD

**Issue by schmelto** [chryz-hub/chryz-hub.github.io#256]
I think the folder structure is little bit unclear due src/assets should be in my opinion only containing images etc not script and css files those should go in separate folders in the src folder 
Something like this:

Index.html
Readme.md
...
* src
  * assets
    * img1.png
    * img2.png
  * js
    * script.js
  * css
    * style.css

Du to this it would also be possible to move the index html into the src folder and deploying the githup page only on the src folder.

**Comment by chryzcodez** [comment]
I'm working on the project....it just remains the responsiveness on display resolution.

I've removed the assets folder, script tag in html and the code and looks generally

**Comment by jomefavourite** [comment]
Okay, could you please show the structure you'll like the folders to be arranged in?

**Comment by schmelto** [comment]
> Okay, could you please show the structure you'll like the folders to be arranged in?

Like mentioned above.

Index.html
Readme.md
...
* src
  * assets
    * img1.png
    * img2.png
  * js
    * script.js
  * css
    * style.css

**Comment by jomefavourite** [comment]
> > Okay, could you please show the structure you'll like the folders to be arranged in?
> 
> Like mentioned above.
> 
> Index.html
> Readme.md
> ...
> 
> * src
>   
>   * assets
>     
>     * img1.png
>     * img2.png
>   * js
>     
>     * script.js
>   * css
>     
>     * style.css

Okay, sorry I didn't notice /assets folder which is the parent to the other folders
@namangupta1399 @Evavic44 I think @schmelto folder structure is very much better

**Comment by namangupta1399** [comment]
Yeah, let's follow this structure.

**Comment by Evavic44** [comment]
I agree.

**Comment by Evavic44** [comment]
I'm making a PR to arrange these files now.
