### ISSUE TITLE
Remove under construction image

### ISSUE THREAD

**Issue by schmelto** [chryz-hub/chryz-hub.github.io#257]
Remove https://www.github.com/chryz-hub/chryz-hub.github.io/tree/master/src%2Fassets%2Fimages%2Funder-construction.jpg du it's no longer needed

**Comment by schmelto** [comment]
@chryzcodez could you add the good forst issue label here think this make a good one

**Comment by Beatrix-droid** [comment]
may i work on this?

**Comment by Evavic44** [comment]
Sure.

**Comment by chryzcodez** [comment]
> may i work on this?

Yeah....it's opensource 😉
