### ISSUE TITLE
Change links hover color

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#271]
Link hover has colors not associated to Chryz-hub. Consider replacing the colors

**Comment by namangupta1399** [comment]
Actually the colors  on hover were on adding Bootstrap to the project. 
Yes, we should change colors according to the website theme.

**Comment by Evavic44** [comment]
> 
> 
> Actually the colors on hover were on adding Bootstrap to the project.
> Yes, we should change colors according to the website theme.

Yeah, fixing that now.
