### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by deephunt3r** [chryz-hub/chryz-hub.github.io#276]
Please invite me to the GitHub Community Organisation.

- #### Name:
  Rakesh

- #### Discord Username(if exists):

  rakesh#9863

**Comment by chryzcodez** [comment]
Hi @deephunt3r 

Welcome to ChryzHub,

Check your email address for the invitation sent, accept it to be a part of the community!

**Comment by deephunt3r** [comment]
> Hi @deephunt3r
> 
> Welcome to ChryzHub,
> 
> Check your email address for the invitation sent, accept it to be a part of the community!

Thank you 🚀
