### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by thuongtruong1009** [chryz-hub/chryz-hub.github.io#328]
### Name

Tran Nguyen Thuong Truong - @thuongtruong1009

### Discord Username (if applicable)

thuongtruong1009

### Additional Context

Hi guys!
My name is thuongtruong1009.
Nice to meet you!
Thank you!

**Comment by chryzcodez** [comment]
Welcome to ChryzHub @thuongtruong1009

**Comment by chryzcodez** [comment]
Welcome to ChryzHub @thuongtruong1009

**Comment by thuongtruong1009** [comment]
> Welcome to ChryzHub @thuongtruong1009

Thank you very much, @chryzcodez! ❤🚀
