### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by 0xMRTT** [chryz-hub/chryz-hub.github.io#391]
### Name

0xMRTT

### Discord Username (if applicable)

0xMRTT#6941

**Comment by chryzcode** [comment]
@0xMRTT Welcome to ChryzHub 🥳🎉

**Comment by 0xMRTT** [comment]
https://github.com/chryz-hub/chryz-hub.github.io/blob/master/CONTRIBUTORS.md?rgh-link-date=2022-08-10T08%3A59%3A06Z

**Comment by 0xMRTT** [comment]
This link is wrong

**Comment by 0xMRTT** [comment]
We cannot add name because there is no file
