### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Salamah-Jimoh** [chryz-hub/chryz-hub.github.io#56]
Please invite me to the GitHub Community Organisation.

- #### Name: Salamah

- #### Discord Username(if exists):

- #### Additional Context:
 On Twitter

I'm willing to explore the opportunities this community has to give

**Comment by chryzcodez** [comment]
> Please invite me to the GitHub Community Organisation.
> 
> * #### Name: Salamah
> 
> * #### Discord Username(if exists):
> 
> * #### Additional Context:
> 
> On Twitter
> I'm willing to explore the opportunities this community has to give

Please join us via our discord channel https://discord.gg/c6RhGwcP5b
