### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#68]
Please invite me to the GitHub Community Organisation.

- #### Name: 

- #### Discord Username(if exists):

- #### Additional Context:

**Comment by jomefavourite** [comment]
Welcome @Evavic44

**Comment by jomefavourite** [comment]
Welcome @Evavic44

**Comment by chryzcodez** [comment]
> Please invite me to the GitHub Community Organisation.
> 
> * #### Name:  Eke Victor
> 
> * #### Discord Username(if exists):
> 
> @Evavic44
> * #### Additional Context:  Through @jomefavourite
> 
> To start contributing on Open Source

welcome
