### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Fuglydami** [chryz-hub/chryz-hub.github.io#69]
Please invite me to the GitHub Community Organisation.

- #### Name: Damilare

- #### Discord Username(if exists):

Askdami#0380 - my discord link

- #### Additional Context:

**Comment by chryzcodez** [comment]
> Please invite me to the GitHub Community Organisation.
> 
> * #### Name: Damilare
> 
> * #### Discord Username(if exists):
> 
> Askdami#0380 - my discord link
> 
> * #### Additional Context:

Hey, Damilare welcome
