### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by frankiefab100** [chryz-hub/chryz-hub.github.io#70]
Please invite me to the GitHub Community Organisation.

- #### Name: Franklin Ohaegbulam

- #### Discord Username(if exists): frankiefab100
- 

- #### Additional Context: I knew about it from a friend
- 
-

**Comment by chryzcodez** [comment]
> Please invite me to the GitHub Community Organisation.
> 
> * #### Name: Franklin Ohaegbulam
> 
> * #### Discord Username(if exists): frankiefab100
> * 
> 
> * #### Additional Context: I knew about it from a friend
> *

Welcome Franklin

**Comment by frankiefab100** [comment]
Thank you
