### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by victor-cody** [chryz-hub/chryz-hub.github.io#75]
Please invite me to the GitHub Community Organisation.

- #### Name:

Victor
- #### Discord Username(if exists):

Victor-ikechukwu

- #### Additional Context: 
Github

**Comment by victor-cody** [comment]
I'm a member 🎉

**Comment by chryzcodez** [comment]
Welcome Victor

**Comment by chryzcodez** [comment]
> I'm a member 🎉

I think it still remains a process! Check your mail to accept the invitation
