### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ehuntober** [chryz-hub/chryz-hub.github.io#79]
Please invite me to the GitHub Community Organisation.

- #### Name:

KELECHI JAMES

- #### Discord Username(if exists):

- #### Additional Context:

**Comment by chryzcodez** [comment]
> Please invite me to the GitHub Community Organisation.
> 
> * #### Name:
> 
> KELECHI JAMES
> 
> * #### Discord Username(if exists):
> 
> * #### Additional Context:

Welcome to the community
