### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by AndrewMill84** [chryz-hub/chryz-hub.github.io#81]
Please invite me to the GitHub Community Organisation.

- #### Name:
Andrew

- #### Discord Username(if exists):
AndrewMill84

- #### Additional Context: 
- found him on discord - via the beginners git link

I like the idea of working on specific things that are going to be used and show value, rather than building thigs for practice that show now real value to anyone

**Comment by chryzcodez** [comment]
> Please invite me to the GitHub Community Organisation.
> 
> * #### Name:
> 
> Andrew
> 
> * #### Discord Username(if exists):
> 
> AndrewMill84
> 
> * #### Additional Context:
> * found him on discord - via the beginners git link
> 
> I like the idea of working on specific things that are going to be used and show value, rather than building thigs for practice that show now real value to anyone

Please, check the messages sent by bot here. To be a member
