### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by i-am-rita** [chryz-hub/chryz-hub.github.io#88]
Please invite me to the GitHub Community Organisation.

- #### Name:

Uzoma Rita

- #### Discord Username(if exists):

Rita

- #### Additional Context: 
Twitter

I want to learn

**Comment by chryzcodez** [comment]
Please accept the invitation sent to your email!

**Comment by i-am-rita** [comment]
Do I need to send an acceptance message?
