### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by NereoOntiveros** [chryz-hub/chryz-hub.github.io#91]
Please invite me to the GitHub Community Organisation.

- #### Name: Nereo Ontiveros

- #### Discord Username(if exists): nontiv

- #### Additional Context: Google

I need to gain experience and grow as a developer, and I would like to collaborate with open source projects.

**Comment by chryzcodez** [comment]
Oh, welcome to the community. I would check if you've met the requirement of the review I gave, if met. I would merge them.

It is also necesary you follow our handles,
<ul><li><a href="https://discord.gg/c6RhGwcP5b">Discord channel</a></li><li><a href="https://www.youtube.com/channel/UCEoxZzYHN1c9ISazmxeCtCQ">Youtube channel</a> by subscribing</li><li><a href="https://twitter.com/ChryzHub">Twitter</a><ul>

You can check more of their functions in the [vision file](https://github.com/chryz-hub/chryz-hub.github.io/blob/master/vision.md) of this community.
