### ISSUE TITLE
Getting a good UI design for the community website

### ISSUE THREAD

**Issue by chryzcodez** [chryz-hub/chryz-hub.github.io#93]
We want to create a UI design for our website. We have started this but we need more contribution to make it standard and perfect.

https://www.figma.com/file/N8ef18pNNEN6Hkht2r44nZ/Chryz-hub?node-id=0%3A1

**Comment by jomefavourite** [comment]
I feel anyone working on the design should create a copy with there name as the title of the artboard like this:

![scrnli_3_12_2021_9-45-43 PM](https://user-images.githubusercontent.com/54733225/110996416-2f703c00-837c-11eb-85ce-fda950f62066.png)

**Comment by chryzcodez** [comment]
> I feel anyone working on the design should create a copy with there name as the title of the artboard like this:
> 
> ![scrnli_3_12_2021_9-45-43 PM](https://user-images.githubusercontent.com/54733225/110996416-2f703c00-837c-11eb-85ce-fda950f62066.png)

Okay share it to the community on discord!

**Comment by Evavic44** [comment]
I thought about that too. Great idea. Will add mine soon.

**Comment by jomefavourite** [comment]
> > I feel anyone working on the design should create a copy with there name as the title of the artboard like this:
> > ![scrnli_3_12_2021_9-45-43 PM](https://user-images.githubusercontent.com/54733225/110996416-2f703c00-837c-11eb-85ce-fda950f62066.png)
> 
> Okay share it to the community on discord!

Okay

**Comment by Evavic44** [comment]
You can add an extra page to work on the UI personally before making the final change on the main page. What do you think?
![Eke's page](https://user-images.githubusercontent.com/62628408/111007457-32c0f300-838f-11eb-987e-99814f2360de.jpg)

**Comment by chryzcodez** [comment]
Ok, that's nice!
