### ISSUE TITLE
I have an idea

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#97]
**Description**
> Hello, can you convert the notes on the project board to issues so there is a tax checklist that can be checked if an issue is completed or accomplished? Don't know if I explained it properly. See image for example.

![project-board](https://user-images.githubusercontent.com/62628408/111015214-02d21980-83a8-11eb-81ce-ae2e8605be73.png)

**Goals**

> - This will help to organize the task list to know the progress being made on every specific task .
> - Help you get a green square if an issue is accomplished

**Comment by chryzcodez** [comment]
Thanks!

**Comment by chryzcodez** [comment]
It's done already!

**Comment by Evavic44** [comment]
Okay. Thanks
